### ISSUE TITLE
Relative Image Paths Not Working

### ISSUE THREAD

**Issue by Elitezen** [Elitezen/easy-trivia-website#1]
Images are not appearing after registering the js.org domain.

**Comment by Turtlepaw** [comment]
![Screenshot_20220302-113451~2](https://user-images.githubusercontent.com/81275769/156405975-81219208-a1d7-4d9d-aaa5-2dea5c38b0ce.png)

I think it's the wrong url

**Comment by Turtlepaw** [comment]
**✅ Check #6**

**Comment by Elitezen** [comment]
Fixed by @Turtlepaw [Here](https://github.com/Elitezen/easy-trivia-website/pull/6)
